### ISSUE TITLE
Text doesn't show up

### ISSUE THREAD

**Issue by nickreiner** [svivian/q2a-ask-notices#4]
There's only an empty box. No text inside it. 

I've entered the warning text in the admin area.

http://i.imgur.com/N1DNJhx.png

I'm using PHP 7, MariaDB and Nginx

Tried switching the theme, still doesn't work.

**Comment by svivian** [comment]
I cannot reproduce here. What did you put in the boxes?

I tried with `where can i` in the "Keywords 1" box and `Can't ask that question` in "Notice 1" and it works fine.
